name: Rewire TypeScript CI

on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: Ubuntu Tests

# TODO: Windows tests don't work; npm test fails
#           - os: windows-latest
#             name: Windows Tests

          - os: macos-latest
            name: MacOS Tests 

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      
    - run: npm install
    - run: npm run build
    - run: npm test
